### ISSUE TITLE
docu: document how to use ZSTOR by command line

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/0-stor_v2#100]
- how to upload/download by using metadata which is given to cmdline and returned (not on tfchain)
- how to verify a namespace is good data, walk over all objects and remote check health (don't download data)
- repair namespace if needed
- check healthy
- ...

**Comment by sasha-astiadi** [comment]
@LeeSmet @maxux im not too sure who we could assign this to

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/home/issues/1345
