### ISSUE TITLE
Remove legacy v2 explorer support

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-stor_v2#106]
- Remove automatic  deployment  of 0-db's
- Remove information from README

This can be done in stages. In a first stage, only the explorer code can be removed and the interface can be left in to not require changes in other code, forcing the NopExplorer to be used.

**Comment by robvanmieghem** [comment]
Next to the automatic deployment of 0-db's, is there a way to add new ones if some are full or decomissioned? I only see the rebuild command in the readme.Is there also a way to know the health/status  or only via prometheus metrics?

**Comment by LeeSmet** [comment]
Currently health is only exposed through prometheus metrics, though it should be fairly straightforward to add a command to just expose this on the cli

**Comment by LeeSmet** [comment]
Explorer specific code and dependencies removed in e3e65dd30c11972d02ebc68f78f1fe4e127286c2

**Comment by robvanmieghem** [comment]
@LeeSmet don't we still need to adapt the readme?

**Comment by robvanmieghem** [comment]
Never mind, saw it was adapted in a later commit
