### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/0-stor_v2#110]
At Dec 21 2021, a v0.3.0-rc12 was made, the actual v0.3.0 has never been released. The latest release is v0.2.0 on Mar 21, 2021.
What is still needed to actually publish a v0.3.0 ?

**Comment by LeeSmet** [comment]
Ideally there would have been more testing, but since that doesn't seem to happen I created the release, issues can be solved in a bugfix release

https://github.com/threefoldtech/0-stor_v2/releases/tag/v0.3.0
