### ISSUE TITLE
Zstor doesn't start when connection to any Zdb times out

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/0-stor_v2#123]
I noticed that when starting up Zstor, if there's a timeout when connecting to any single Zdb in the config, Zstor just exits with an error. This means that the operator or some automation must be prepared to remove failed backends from the config whenever Zstor restarts. I think the more sensible behavior is to start up and continue operating if there are sufficient live backends to do so.

**Comment by iwanbk** [comment]
>  I noticed that when starting up Zstor, if there's a timeout when connecting to any single Zdb in the config, Zstor just exits with an error

In my tests, above behavior only happened if it happens to meta zdb.
If it is for the backend, `zstor` could start properly.

> I think the more sensible behavior is to start up and continue operating if there are sufficient live backends to do so.

It already happens for the data backends.

For meta backends, actually all the 4 backends must be up
See the readme 

> Because the system is designed to prioritize recoverability over availability, writers will be rejected if the metadata storage is in the degraded state, that is, not all 4 stores are available and writeable.

**Comment by iwanbk** [comment]
i got more findings when working on #120 , will check it again

**Comment by iwanbk** [comment]
I use these configs:
- minimal shards = 4
- expected shards = 6

I've tested these scenario:
1. 4 meta, 6 data shards
  - `zstor monitor` started
  - `zstore store` OK

2. 4 meta, 4-5 data shards
  - `zstor monitor` started
  - `zstor store` failed with `Zstor error: error during configuration: unable to find a valid configuration due to redundancy settings`
3. 4 meta, 3 data shards
 - `zstor monitor` started
 - store failed
 
4. 3 meta, 6 data shards
- `zstor monitor` failed to start
- `store` &  `retrieve` failed

For case number 4, i think the expectation is:
- `zstor monitor` started
- `zstor store` failed
- `zstor retrieve` OK

CMIIW @LeeSmet

**Comment by LeeSmet** [comment]
You're right that for case 4 retrieves should still function, so that is indeed a bug.
For case 2, does the load still work?

**Comment by iwanbk** [comment]
> For case 2, does the load still work?

you mean `retrieve`?
Yes, it works

**Comment by scottyeager** [comment]
Thanks for the analysis and additional testing @iwanbk. That's a good point that we shouldn't expect to be able to write when some metadata backend is down.

My expectation would be that Zstor always starts (with a valid config file), but actions are blocked if there's some degradation. Even in the case that only one or zero metadata backends is available, I think it's better to start and block both reads and writes.

**Comment by iwanbk** [comment]
because there are other things come up during this issue discussion, i created another issue to track all the related things.

Please check #127 @scottyeager @LeeSmet

**Comment by iwanbk** [comment]
for the main issue here 

> Zstor doesn't start when connection to any Zdb times out

It should be fixed by #128 PR 

I also blocked the `write` when one of the meta is down.

**Comment by iwanbk** [comment]
@scottyeager 
The PR #128 has been merged, i re-assigned this issue to you for checking or closing it.

**Comment by scottyeager** [comment]
I have verified the new behaviors:

* Zstor starts when some metadata backends are unreachable
* Writes are blocked with an error when fewer than 4 metadata backends are available
* Reads succeed as long as 2 metadata backends are okay
