### ISSUE TITLE
Prepare a release with TLS feature 

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/0-stor_v2#25]
Continuing on https://github.com/threefoldtech/0-stor_v2/issues/16

Also include in the https://github.com/threefoldtech/k3os image

**Comment by LeeSmet** [comment]
Prerelease has been made: https://github.com/threefoldtech/0-stor_v2/releases/tag/v0.2.0-rc.1

For inclusion in the image, that will be done on the final release (also, that's actually a zos issue :) )
