### ISSUE TITLE
implementation of metadata storage on top of 0-db

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-stor_v2#39]
- metastor should be refactored to become an interface
- an implementation should be added for this on top of 0-db
  - 0-db runs in sequential mode for data storage. For metadata this will need to be user mode
  - we might need to rethink how some things are stored since we loose the ability to do efficient range scans based on prefixes
- instead of a server side cluster, we should have dispersed encoding in the client and chunks saved in multiple backends

**Comment by maxux** [comment]
That make me thinking about some pre-check: using `NSINFO`, checking running mode, we need `seq` for data and `user` for metadata.
