### ISSUE TITLE
Investigate different encodig algorithms

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-stor_v2#40]
While the current dispersed encoding algorithm is well known and battle tested, a new class of encodings, known as raptor codes, was discovered in early 2000. The most advanced version,  `RaptorQ` seems to achieve high throughput rates. Its probably worth investigating if these can be used as a suitable (alternative) encoding. They seem to be already used with great success in storage systems, [as described here](http://www1.icsi.berkeley.edu/~pooja/liquid_paper.pdf)

**Comment by sasha-astiadi** [comment]
helm chart for k8s deployment issue https://github.com/threefoldtech/quantum-storage/issues/8
protection of zdb https://github.com/threefoldtech/quantum-storage/issues/12
monitoring issue https://github.com/threefoldtech/quantum-storage/issues/13
