### ISSUE TITLE
No function with VDC provided etcd

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/0-stor_v2#41]
I've enabled QSFS on a VDC and downloaded the generated zstor config file. When I run zstor (built from ffae44c, also testing with provided 0.2 binary) using this config, it simply hangs and does not write anything to the log file. Replacing the etcd with a local instance works.

Here's the etcd info:

```
[meta.config]
endpoints = ["https://etcdqs-29108.webg1test.grid.tf:2379"]
prefix = "mounted"
username = "root"
password = "[let me know if you need this]"
```

I can ping the etcd server successfully, but attempting operations with `etcdctl` also fails.

**Comment by despiegk** [comment]
this will be replaced by a new version of quantum safe filesystem
no need to resolve using etcd
