### ISSUE TITLE
define all detailed issues & FR needed for 2.8 release QSFS

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/0-stor_v2#42]
see https://github.com/threefoldtech/home/issues/1044

ask KDS to review

**Comment by despiegk** [comment]
sort through all bugs/fr/... attach to right release of QSFS project which can get linked to story

**Comment by sasha-astiadi** [comment]
helm chart for k8s deployment issue https://github.com/threefoldtech/quantum-storage/issues/8
protection of zdb https://github.com/threefoldtech/quantum-storage/issues/12
monitoring issue https://github.com/threefoldtech/quantum-storage/issues/13
