### ISSUE TITLE
Add async store option and prioritize commands

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/0-stor_v2#84]
store commands currently block until it's processed and the handling is done sequentially causing a lot of processes to be created and high memory consumption. zdb issue hooks like `retrieve-data` and blocks until the hook returns, causing zdbfs also to block. with the sequential handling, it means the filesystem will be blocked until all previous store finishes.

Improvements:
- Add async option to store subcommand to return immediately and queue the command internally.
- Add another actor to prioritize the commands, it should handle stores as long as no other command type arrive.
- Handle SIGTERM and SIGINT to block until all store command finishes (SIGKILL should be semi-handlable by persisting the commands queue).
- Delete `/var/run/zstor.sock` before binding to it. What happens then if another zstor daemon was running is that the old one will serve the already accepted connections and won't be able to accept the next and it'll shutdown. Another solution is to have a `lock` file and prevent starting if the lock is acquired.
- When zdb crashes the connection should be reestablished, currently it continues to fail due to `Broken pipe` error. And failed stores should be retried.

**Comment by LeeSmet** [comment]
To my understanding, this is implemented now
