### ISSUE TITLE
TC196: deploy QSFS

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/0-stor_v2#85]
Setting up/exporting the TWIN_ID and MNEMONICS, SSH Key
Setting up the required variables and provisioning the VM

As the result the output for the "metadata" is empty, only showing the ygg IP, but not able to SSH into the VM

The backend IP is only shown shen running "terraform destroy" then it specified which resources will be destroyed listing the backup.

Cannot see any output in the browser either when navigating to the ygg address

**Comment by LeeSmet** [comment]
This seems to be an issue related to the way of deploying, so for terraform it seems. Given the age of the issue, I'll close it. If it happens again, issue should be created in the terraform repo
